package HelloWorld;


/**
* HelloWorld/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* Tuesday, 26 February 2019 10:49:31 o'clock GMT
*/

public interface HelloOperations 
{

  //
  String hello_world ();
} // interface HelloOperations
